### PR TITLE
release-pleebo-1.1.2

### PR DESCRIPTION
**Pull request by BranfordTGbieor**

### CODE REVIEW

**Comment by brandones** [comment]
Hey Branford! Thanks for your work. Of the PRs you've merged in today, this is the one that was merged correctly. You see how in "Files changed" above, it shows the changes you made? That's very helpful. Please keep using the "Merge" button to merge PRs.

**Comment by BranfordTGbieor** [comment]
Thanks for the tip @brandones! Appreciate man.

**Comment by brandones** [comment]
No worries about what's already done. Just make sure to use the "Merge" button going forward. We should (almost) never push directly to `master`.

I just documented my usual git workflow on my blog earlier today, if you're interested: https://stderr.brandonistenes.com/my-git-workflow/

**Comment by BranfordTGbieor** [comment]
Thank you @brandones.

**Pull request merged**
