### PR TITLE
Removing unused liquibase steps

### PR DESCRIPTION
**Pull request by jmbabazi**

### CODE REVIEW

**Comment by mogoodrich** [comment]
This generally looks good, but I suspect we are going to run into whatever problems I ran into last time with removing (and that I've forgotten the details of!).  Do we want to coordinate when we want to merge this in to a time when we are sure we can test?

**Comment by brandones** [comment]
Any reason not to just delete the code? It will always be available in the git history.

**Comment by jmbabazi** [comment]
Thanks @mogoodrich , lets coordinate when we can merge this in. We can remove this if we think the history is enough @brandones

**Comment by brandones** [comment]
@jmbabazi @mogoodrich Should we close this as stale? Or should we fix it up and merge it in?

**Comment by mogoodrich** [comment]
Probably makes sense to close as stale at this point, thoughts @jmbabazi ?

**Pull request closed without merging**
