### PR TITLE
UHM-3912 - Disable session persistence across server restarts

### PR DESCRIPTION
**Pull request by mseaton**

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
Defer to you on the specifics!

**Comment by mseaton** [comment]
> Defer to you on the specifics!

So you are good merging this in @mogoodrich ?  Just want to make sure timing is good for this to be tested before a possible rollout somewhere.

**Comment by mogoodrich** [comment]
Oh, thanks, good point @mseaton... can we wait until things have stabilized a bit?  I have a bunch of deploys to do to CES and Haiti to do the pipeline changes you'd asked for, and I'd like to do them as soon as I've confirmed the build is working again.

**Comment by mogoodrich** [comment]
@mseaton  just noticed this old PR that is still open.  I'm fine with merging now... :)

**Pull request merged**
